project:
  type: book
  output-dir: docs

book:
  title: "Estimation of risk-sharing model with limited commitment"
  author: "Mizuhiro Suzuki"
  date: ""
  chapters:
    - index.qmd
    - dataprep.qmd
    - full_hom.qmd
    - lc_hom_model.qmd
    - lc_hom_static.qmd
    - lc_hom_estimation.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

